# Generated by Django 5.1.5 on 2025-02-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='mainproducts/'),
        ),
    ]
