# Generated by Django 5.1.5 on 2025-02-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_mainproduct_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('MainProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mainproduct')),
            ],
        ),
    ]
