# Generated by Django 5.1.5 on 2025-03-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_features_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
