# Generated by Django 5.1.5 on 2025-02-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careerform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerForm',
        ),
    ]
