# Generated by Django 5.1.5 on 2025-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='email2',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
