# Generated by Django 5.1.5 on 2025-03-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeosDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('designation', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ceos_desk/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
