# Generated by Django 5.1.5 on 2025-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_overview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_mission_vision/')),
            ],
        ),
    ]
