# Generated by Django 5.1.5 on 2025-02-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_overview', '0002_ourmissionvision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourmissionvision',
            old_name='image',
            new_name='icon',
        ),
    ]
