# Generated by Django 5.1.5 on 2025-03-22 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_overview', '0004_ourvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whowearesection',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
