# Generated by Django 5.1.5 on 2025-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_excellence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Manufacturing_infrastructure/')),
            ],
        ),
    ]
