# Generated by Django 5.1.5 on 2025-02-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_excellence', '0002_manufacturinginfrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringCapabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='measuring_capabilities/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='measuring_capabilities/')),
            ],
        ),
    ]
