# Generated by Django 5.1.5 on 2025-03-10 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='milestones/')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='milestone_images/')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='milestone.milestone')),
            ],
        ),
    ]
